version: '3.6'

x-base: &base
  build: .
  environment:
    DJANGO_SETTINGS_MODULE: 'montgomery.settings'
  ports:
    - 8000
  volumes:
    - .:/app/montgomery

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: montgomery
      POSTGRES_PASSWORD: montgomery
      POSTGRES_DB: montgomery
    command: -c fsync=off
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    <<: *base
    entrypoint: gunicorn
    command: --reload --workers=5 --threads=2 --max-requests 1000 --bind 0.0.0.0:8000 montgomery.wsgi
    ports:
      - 8000
    depends_on:
      - db

  api:
    <<: *base
    entrypoint: python
    command: server.py
    ports:
      - 8080
    depends_on:
      - app
      - db

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
      - api

volumes:
  pgdata:
